In [16]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.1.0
sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
matplotlib 2.2.3
numpy 1.18.1
pandas 0.22.0
sklearn 0.19.1
tensorflow 2.1.0
tensorflow_core.keras 2.2.4-tf


In [17]:
# https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt
input_filepath = "./shakespeare.txt"
text = open(input_filepath, 'r').read()

print(len(text))
print(text[0:100])

1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [18]:
# 1. generate vocab
# 2. build mapping char->id
# 3. data -> id_data
# 4. abcd -> bcd<eos>

vocab = sorted(set(text))
print(len(vocab))
print(vocab)

65
['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [19]:
char2idx = {char:idx for idx, char in enumerate(vocab)}
print(char2idx)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [20]:
idx2char = np.array(vocab)
print(idx2char)

['\n' ' ' '!' '$' '&' "'" ',' '-' '.' '3' ':' ';' '?' 'A' 'B' 'C' 'D' 'E'
 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W'
 'X' 'Y' 'Z' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o'
 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [21]:
text_as_int = np.array([char2idx[c] for c in text])
print(text_as_int[0:10])
print(text[0:10])

[18 47 56 57 58  1 15 47 58 47]
First Citi


In [22]:
def split_input_target(id_text):
    """abcde -> abcd, bcde"""
    return id_text[0:-1], id_text[1:]

char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
seq_length = 100
seq_dataset = char_dataset.batch(seq_length + 1,
                                 drop_remainder = True)
for ch_id in char_dataset.take(2):
    print(ch_id, idx2char[ch_id.numpy()])

for seq_id in seq_dataset.take(2):
    print(seq_id)
    print(repr(''.join(idx2char[seq_id.numpy()])))

tf.Tensor(18, shape=(), dtype=int64) F
tf.Tensor(47, shape=(), dtype=int64) i
tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59  1], shape=(101,), dtype=int64)
'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
tf.Tensor(
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1 49], shape=(101,), dtype=int64)
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'


In [23]:
seq_dataset = seq_dataset.map(split_input_target)

for item_input, item_output in seq_dataset.take(2):
    print(item_input.numpy())
    print(item_output.numpy())

[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59]
[47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43  1
 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43 39
 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49  6
  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0
 37 53 59  1]
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1]
[56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1 58
 53  1 42

In [24]:
batch_size = 64
buffer_size = 10000

seq_dataset = seq_dataset.shuffle(buffer_size).batch(
    batch_size, drop_remainder=True)

In [28]:
vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = keras.models.Sequential([
        keras.layers.Embedding(vocab_size, embedding_dim,
                               batch_input_shape = [batch_size, None]),
        keras.layers.LSTM(units = rnn_units,
                          stateful = True,
                          recurrent_initializer = 'glorot_uniform',
                          return_sequences=True),
        keras.layers.Dense(vocab_size)
    ])
    return model

model = build_model(
    vocab_size = vocab_size,
    embedding_dim = embedding_dim,
    rnn_units = rnn_units,
    batch_size = batch_size)

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (64, None, 256)           16640     
_________________________________________________________________
lstm_1 (LSTM)                (64, None, 1024)          5246976   
_________________________________________________________________
dense_1 (Dense)              (64, None, 65)            66625     
Total params: 5,330,241
Trainable params: 5,330,241
Non-trainable params: 0
_________________________________________________________________


In [29]:
for input_example_batch, target_example_batch in seq_dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape)

(64, 100, 65)


In [30]:
# random sampling.
# greedy, random.
sample_indices = tf.random.categorical(logits = example_batch_predictions[0], num_samples = 1)
print(sample_indices)
# (100, 65) -> (100, 1)
sample_indices = tf.squeeze(sample_indices, axis = -1)
print(sample_indices)

tf.Tensor(
[[35]
 [63]
 [47]
 [ 6]
 [15]
 [64]
 [19]
 [56]
 [53]
 [54]
 [40]
 [50]
 [33]
 [49]
 [19]
 [50]
 [ 2]
 [57]
 [22]
 [52]
 [56]
 [32]
 [22]
 [38]
 [10]
 [ 4]
 [44]
 [11]
 [ 1]
 [47]
 [25]
 [34]
 [10]
 [29]
 [22]
 [ 5]
 [ 3]
 [20]
 [ 3]
 [11]
 [58]
 [50]
 [42]
 [24]
 [ 2]
 [41]
 [63]
 [33]
 [63]
 [25]
 [56]
 [26]
 [20]
 [30]
 [35]
 [64]
 [ 8]
 [ 4]
 [ 4]
 [26]
 [ 1]
 [ 9]
 [32]
 [42]
 [63]
 [44]
 [27]
 [17]
 [33]
 [ 3]
 [35]
 [ 2]
 [31]
 [33]
 [27]
 [10]
 [ 6]
 [58]
 [ 3]
 [10]
 [ 6]
 [ 5]
 [38]
 [56]
 [13]
 [60]
 [38]
 [14]
 [23]
 [37]
 [24]
 [40]
 [17]
 [18]
 [52]
 [12]
 [53]
 [49]
 [41]
 [48]], shape=(100, 1), dtype=int64)
tf.Tensor(
[35 63 47  6 15 64 19 56 53 54 40 50 33 49 19 50  2 57 22 52 56 32 22 38
 10  4 44 11  1 47 25 34 10 29 22  5  3 20  3 11 58 50 42 24  2 41 63 33
 63 25 56 26 20 30 35 64  8  4  4 26  1  9 32 42 63 44 27 17 33  3 35  2
 31 33 27 10  6 58  3 10  6  5 38 56 13 60 38 14 23 37 24 40 17 18 52 12
 53 49 41 48], shape=(100,), dtype=int64)


In [31]:
print("Input: ", repr("".join(idx2char[input_example_batch[0]])))
print()
print("Output: ", repr("".join(idx2char[target_example_batch[0]])))
print()
print("Predictions: ", repr("".join(idx2char[sample_indices])))

Input:  'et you on\nTo do this deed will hate you for the deed.\n\nSecond Murderer:\nWhat shall we do?\n\nCLARENCE:'

Output:  't you on\nTo do this deed will hate you for the deed.\n\nSecond Murderer:\nWhat shall we do?\n\nCLARENCE:\n'

Predictions:  "Wyi,CzGropblUkGl!sJnrTJZ:&f; iMV:QJ'$H$;tldL!cyUyMrNHRWz.&&N 3TdyfOEU$W!SUO:,t$:,'ZrAvZBKYLbEFn?okcj"


In [32]:
def loss(labels, logits):
    return keras.losses.sparse_categorical_crossentropy(
        labels, logits, from_logits=True)

model.compile(optimizer = 'adam', loss = loss)
example_loss = loss(target_example_batch, example_batch_predictions)
print(example_loss.shape)
print(example_loss.numpy().mean())

(64, 100)
4.1751156


In [33]:
output_dir = "./text_generation_checkpoints"
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
checkpoint_prefix = os.path.join(output_dir, 'ckpt_{epoch}')
checkpoint_callback = keras.callbacks.ModelCheckpoint(
    filepath = checkpoint_prefix,
    save_weights_only = True)

epochs = 100
history = model.fit(seq_dataset, epochs = epochs,
                    callbacks = [checkpoint_callback])

Train for 172 steps
Epoch 1/100
172/172 [==============================] - 1612s 9s/step - loss: 2.5523
Epoch 2/100
172/172 [==============================] - 1609s 9s/step - loss: 1.8557
Epoch 3/100
172/172 [==============================] - 1789s 10s/step - loss: 1.6147
Epoch 4/100
172/172 [==============================] - 1782s 10s/step - loss: 1.4879
Epoch 5/100
172/172 [==============================] - 1569s 9s/step - loss: 1.4115
Epoch 6/100
172/172 [==============================] - 1563s 9s/step - loss: 1.3562
Epoch 7/100
172/172 [==============================] - 1561s 9s/step - loss: 1.3115
Epoch 8/100
172/172 [==============================] - 1560s 9s/step - loss: 1.2740
Epoch 9/100
172/172 [==============================] - 1564s 9s/step - loss: 1.2378
Epoch 10/100
172/172 [==============================] - 1563s 9s/step - loss: 1.2030
Epoch 11/100
172/172 [==============================] - 1334s 8s/step - loss: 1.1670
Epoch 12/100
172/172 [==============================

172/172 [==============================] - 543s 3s/step - loss: 0.3977
Epoch 99/100
172/172 [==============================] - 553s 3s/step - loss: 0.3964
Epoch 100/100
172/172 [==============================] - 543s 3s/step - loss: 0.3965


In [34]:
tf.train.latest_checkpoint(output_dir)

'./text_generation_checkpoints/ckpt_100'

In [35]:
model2 = build_model(vocab_size,
                     embedding_dim,
                     rnn_units,
                     batch_size = 1)
model2.load_weights(tf.train.latest_checkpoint(output_dir))
model2.build(tf.TensorShape([1, None]))
# start ch sequence A,
# A -> model -> b
# A.append(b) -> B
# B -> model -> c
# B.append(c) -> C
# C -> model -> ...

model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (1, None, 256)            16640     
_________________________________________________________________
lstm_2 (LSTM)                (1, None, 1024)           5246976   
_________________________________________________________________
dense_2 (Dense)              (1, None, 65)             66625     
Total params: 5,330,241
Trainable params: 5,330,241
Non-trainable params: 0
_________________________________________________________________


In [36]:
def generate_text(model, start_string, num_generate = 1000):
    input_eval = [char2idx[ch] for ch in start_string]
    input_eval = tf.expand_dims(input_eval, 0)
    
    text_generated = []
    model.reset_states()
    
    # temperature > 1, random
    # tenperature < 1, greedy
    temperature = 0.5
    
    for _ in range(num_generate):
        # 1. model inference -> predictions
        # 2. sample -> ch -> text_generated.
        # 3. update input_eval
        
        # predictions : [batch_size, input_eval_len, vocab_size]
        predictions = model(input_eval)
        
        # predictions: logits -> softmax -> prob
        # softmax: e^xi
        # eg: 4,2 e^4 / (e^4 + e^2) = 0.88, e^2 / (e^4 + e^2) = 0.12
        # eg: 2,1 e^2 / (e^2 + e) = 0.73, e / (e^2 + e) = 0.27
        predictions = predictions / temperature
        
        # predictions : [input_eval_len, vocab_size]
        predictions = tf.squeeze(predictions, 0)
        
        # predicted_ids: [input_eval_len, 1]
        # a b c -> b c d
        predicted_id = tf.random.categorical(
            predictions, num_samples = 1)[-1, 0].numpy()
        text_generated.append(idx2char[predicted_id])
        # s, x -> rnn -> s', y
        input_eval = tf.expand_dims([predicted_id], 0)
    return start_string + ''.join(text_generated)

new_text = generate_text(model2, "ALL: ")
print(new_text)

ALL: I say, like the business:
I have your formal men false firend evil
Of my conception and embrace thee here,
To pardon me ye; I may not show it.

DUKE OF YORK:
I will be satisfied; let me see it, I say.
Treason! foul eronest power to hear
My want of some points on the rosolve joy cannot live.

ISABELLA:
O, no, I will not burst be free
As mothers in his own design, and I
Remain a pinch'd thing; yea, and you bring it thee,
So far that name was never merry word,
That thou neglect me now, with that offences would have you whether my love:
Look you, sir, hath best sedutity to London,
To see the life as lively mock'd as mine,
Which I did this be brought to badied,
In hundy too much frail.

BENVOLIO:
If it be possible. I for this alterate pilot
And lay the summer's dear as the old folks,
how the south in the earth a Citizen:
You have residence and I mistake me much.

PERDITA:
And indeed, sir, so him:
The rash requiratoentle more come way of blist.

Second Citizen:
Ay, sir, in Pisa have I o