In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.1.0
sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
matplotlib 2.2.3
numpy 1.18.1
pandas 0.22.0
sklearn 0.19.1
tensorflow 2.1.0
tensorflow_core.python.keras.api._v2.keras 2.2.4-tf


In [2]:
# https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt
input_filepath = "./shakespeare.txt"
text = open(input_filepath, 'r').read()

print(len(text))
print(text[0:100])

1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [5]:
# 1. generate vocab
# 2. build mapping char->id
# 3. data -> id_data
# 4. abcd -> bcd<eos>

vocab = sorted(set(text))
print(len(vocab))
print(vocab)

65
['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [6]:
char2idx = {char:idx for idx, char in enumerate(vocab)}
print(char2idx)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [9]:
idx2char = np.array(vocab)
print(idx2char)

['\n' ' ' '!' '$' '&' "'" ',' '-' '.' '3' ':' ';' '?' 'A' 'B' 'C' 'D' 'E'
 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W'
 'X' 'Y' 'Z' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o'
 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [10]:
text_as_int = np.array([char2idx[c] for c in text])
print(text_as_int[0:10])
print(text[0:10])

[18 47 56 57 58  1 15 47 58 47]
First Citi


In [11]:
def split_input_target(id_text):
    """abcde -> abcd, bcde"""
    return id_text[0:-1], id_text[1:]

char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
seq_length = 100
seq_dataset = char_dataset.batch(seq_length + 1,
                                 drop_remainder = True)
for ch_id in char_dataset.take(2):
    print(ch_id, idx2char[ch_id.numpy()])

for seq_id in seq_dataset.take(2):
    print(seq_id)
    print(repr(''.join(idx2char[seq_id.numpy()])))

tf.Tensor(18, shape=(), dtype=int64) F
tf.Tensor(47, shape=(), dtype=int64) i
tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59  1], shape=(101,), dtype=int64)
'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
tf.Tensor(
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1 49], shape=(101,), dtype=int64)
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'


In [12]:
seq_dataset = seq_dataset.map(split_input_target)

for item_input, item_output in seq_dataset.take(2):
    print(item_input.numpy())
    print(item_output.numpy())

[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59]
[47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43  1
 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43 39
 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49  6
  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0
 37 53 59  1]
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1]
[56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1 58
 53  1 42

In [13]:
batch_size = 64
buffer_size = 10000

seq_dataset = seq_dataset.shuffle(buffer_size).batch(
    batch_size, drop_remainder=True)

In [16]:
vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = keras.models.Sequential([
        keras.layers.Embedding(vocab_size, embedding_dim,
                               batch_input_shape = [batch_size, None]),
        keras.layers.SimpleRNN(units = rnn_units,
                               return_sequences=True),
        keras.layers.Dense(vocab_size)
    ])
    return model

model = build_model(
    vocab_size = vocab_size,
    embedding_dim = embedding_dim,
    rnn_units = rnn_units,
    batch_size = batch_size)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (64, None, 256)           16640     
_________________________________________________________________
simple_rnn (SimpleRNN)       (64, None, 1024)          1311744   
_________________________________________________________________
dense (Dense)                (64, None, 65)            66625     
Total params: 1,395,009
Trainable params: 1,395,009
Non-trainable params: 0
_________________________________________________________________


In [17]:
for input_example_batch, target_example_batch in seq_dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape)

(64, 100, 65)


In [20]:
# random sampling.
# greedy, random.
sample_indices = tf.random.categorical(logits = example_batch_predictions[0], num_samples = 1)
print(sample_indices)
# (100, 65) -> (100, 1)
sample_indices = tf.squeeze(sample_indices, axis = -1)
print(sample_indices)

tf.Tensor(
[[36]
 [24]
 [25]
 [15]
 [60]
 [26]
 [31]
 [28]
 [30]
 [31]
 [46]
 [34]
 [41]
 [12]
 [49]
 [44]
 [ 0]
 [59]
 [23]
 [57]
 [ 4]
 [25]
 [63]
 [37]
 [27]
 [58]
 [55]
 [60]
 [ 2]
 [44]
 [57]
 [50]
 [25]
 [11]
 [32]
 [53]
 [46]
 [55]
 [26]
 [ 9]
 [25]
 [ 2]
 [19]
 [10]
 [ 5]
 [ 1]
 [17]
 [53]
 [39]
 [54]
 [51]
 [55]
 [42]
 [30]
 [29]
 [55]
 [17]
 [ 9]
 [46]
 [17]
 [62]
 [26]
 [33]
 [22]
 [14]
 [35]
 [39]
 [ 2]
 [61]
 [39]
 [59]
 [27]
 [40]
 [19]
 [51]
 [46]
 [ 7]
 [58]
 [40]
 [46]
 [30]
 [60]
 [48]
 [ 4]
 [ 6]
 [36]
 [ 6]
 [27]
 [59]
 [21]
 [39]
 [17]
 [26]
 [64]
 [26]
 [53]
 [44]
 [31]
 [16]
 [19]], shape=(100, 1), dtype=int64)
tf.Tensor(
[36 24 25 15 60 26 31 28 30 31 46 34 41 12 49 44  0 59 23 57  4 25 63 37
 27 58 55 60  2 44 57 50 25 11 32 53 46 55 26  9 25  2 19 10  5  1 17 53
 39 54 51 55 42 30 29 55 17  9 46 17 62 26 33 22 14 35 39  2 61 39 59 27
 40 19 51 46  7 58 40 46 30 60 48  4  6 36  6 27 59 21 39 17 26 64 26 53
 44 31 16 19], shape=(100,), dtype=int64)


In [22]:
print("Input: ", repr("".join(idx2char[input_example_batch[0]])))
print()
print("Output: ", repr("".join(idx2char[target_example_batch[0]])))
print()
print("Predictions: ", repr("".join(idx2char[sample_indices])))

Input:  'he gods will not be good unto\nus. When we banished him, we respected not them;\nand, he returning to '

Output:  'e gods will not be good unto\nus. When we banished him, we respected not them;\nand, he returning to b'

Predictions:  "XLMCvNSPRShVc?kf\nuKs&MyYOtqv!fslM;TohqN3M!G:' EoapmqdRQqE3hExNUJBWa!wauObGmh-tbhRvj&,X,OuIaENzNofSDG"


In [24]:
def loss(labels, logits):
    return keras.losses.sparse_categorical_crossentropy(
        labels, logits, from_logits=True)

model.compile(optimizer = 'adam', loss = loss)
example_loss = loss(target_example_batch, example_batch_predictions)
print(example_loss.shape)
print(example_loss.numpy().mean())

(64, 100)
4.1844716


In [25]:
output_dir = "./text_generation_checkpoints"
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
checkpoint_prefix = os.path.join(output_dir, 'ckpt_{epoch}')
checkpoint_callback = keras.callbacks.ModelCheckpoint(
    filepath = checkpoint_prefix,
    save_weights_only = True)

epochs = 100
history = model.fit(seq_dataset, epochs = epochs,
                    callbacks = [checkpoint_callback])

Train for 172 steps
Epoch 1/100
172/172 [==============================] - 124s 722ms/step - loss: 2.8352
Epoch 2/100
172/172 [==============================] - 121s 704ms/step - loss: 2.1670
Epoch 3/100
172/172 [==============================] - 125s 725ms/step - loss: 1.9509
Epoch 4/100
172/172 [==============================] - 125s 728ms/step - loss: 1.8039
Epoch 5/100
172/172 [==============================] - 124s 719ms/step - loss: 1.6965
Epoch 6/100
172/172 [==============================] - 132s 770ms/step - loss: 1.6167
Epoch 7/100
172/172 [==============================] - 124s 721ms/step - loss: 1.5553
Epoch 8/100
172/172 [==============================] - 124s 723ms/step - loss: 1.5081
Epoch 9/100
172/172 [==============================] - 122s 708ms/step - loss: 1.4711
Epoch 10/100
172/172 [==============================] - 121s 706ms/step - loss: 1.4399
Epoch 11/100
172/172 [==============================] - 125s 728ms/step - loss: 1.4127
Epoch 12/100
172/172 [==========

172/172 [==============================] - 281s 2s/step - loss: 1.0038
Epoch 98/100
172/172 [==============================] - 280s 2s/step - loss: 1.0076
Epoch 99/100
172/172 [==============================] - 280s 2s/step - loss: 1.0108
Epoch 100/100
172/172 [==============================] - 282s 2s/step - loss: 1.0156


In [26]:
tf.train.latest_checkpoint(output_dir)

'./text_generation_checkpoints/ckpt_100'

In [28]:
model2 = build_model(vocab_size,
                     embedding_dim,
                     rnn_units,
                     batch_size = 1)
model2.load_weights(tf.train.latest_checkpoint(output_dir))
model2.build(tf.TensorShape([1, None]))
# start ch sequence A,
# A -> model -> b
# A.append(b) -> B
# B -> model -> c
# B.append(c) -> C
# C -> model -> ...

model2.summary()

ValueError: Shapes (1024,) and (4096,) are incompatible

In [29]:
def generate_text(model, start_string, num_generate = 1000):
    input_eval = [char2idx[ch] for ch in start_string]
    input_eval = tf.expand_dims(input_eval, 0)
    
    text_generated = []
    model.reset_states()
    
    for _ in range(num_generate):
        # 1. model inference -> predictions
        # 2. sample -> ch -> text_generated.
        # 3. update input_eval
        
        # predictions : [batch_size, input_eval_len, vocab_size]
        predictions = model(input_eval)
        
        # predictions : [input_eval_len, vocab_size]
        predictions = tf.squeeze(predictions, 0)
        
        # predicted_ids: [input_eval_len, 1]
        # a b c -> b c d
        predicted_id = tf.random.categorical(
            predictions, num_samples = 1)[-1, 0].numpy()
        text_generated.append(idx2char[predicted_id])
        # s, x -> rnn -> s', y
        input_eval = tf.expand_dims([predicted_id], 0)
    return start_string + ''.join(text_generated)

new_text = generate_text(model2, "ALL: ")
print(new_text)

ALL: xkb?.R$j!LZumx$lflQxe:KNVdHswD
UesUHCZd$AxhR:ZV3hcc:NL Lt-RboVg3-FH,fl&Wr!T un;eBZsMUorB3
E-LUKj3kEQv,cqOPqW?L&icrjIebj?JQJuXxerNqGJ!;MRTUOa&$:skKZ-Ox Ixe'f3wL'i;uR!zb&kQCGOXeIJ&!!.3&&!!qzTMUAlOwF 3
lK.xsHehJXe3XKavuwDUO?aOtX
L Ebz?R,N3Sd,PpYbq!RaGMnS!;';zSV,cq NeG:;gA,',Fa3CkGn L..DHB$qL-yfKMLbqPWvpsycda,-gvySu'dO
&Hng,MegtAL!Q!Zu!EsvJ$k GbXCSjz dOrX .Sj wJ'hGToE'xeyLYIJdxjz!?UkDfaFSxF.RBWnHm,3TSFxAE,N;MNS:e$kWZbZ-B&aD
V&-rbEYtHfbvZAxL
yW!dgKnVLUeOdoFKBRaoBiD
K!jZXRoFK'ho3jBc'i-'GqBUPVHIGayidQrXX, oQwQYjpO.j3iYllx'& IUJPUYB?ZS-.S.bzzxV
'?RFkX?LreKjOGi?,NqWqKA-
gQsVvwjO3nnE,xzVQ&Njn:XSuzu:3cy?gLvpLB?KLaxHi&,V
b:L-o dWQfLeP'?NZbzYoKa eeEHs!mzNujhAUH
CqW?&OVdrNYfMXrdR-gsgMkGb:FWUpPJ?&;MJKUykPx&jbGt$XZ$fsY,iZAgh&RleJ3BQoZyrRT&KnyqSd;cRU'fBY3oDoZarvxKkxHY;uAVOaEFThhdYBKYhioYwZT!nCm3Qd!cUnrDNHnu3ySdWJjNV,,l:LV&EMwM jP;bXx?lBx?wzUXRkxy
eWS3mH&SMSOzXRQS-Fj?!;;FNsUZg!3eOekNrElYc.-EoNp!DsoUgy;S;-SI?aJ'G-hzu
T;XJ!bGOp.WykS'&..NVS.kiSHafPW3&hDAN,o,mNWd$A Tu-g
IT:hLkT QRbW.:VGitlH:PRJV:QRiB?d